wandb_version: 1

object:
  desc: null
  value: fine-tune
id:
  desc: null
  value: ft-v6g0Kid5b6R8xO5LiylaTmDv
hyperparams:
  desc: null
  value:
    n_epochs: 2
    batch_size: 2
    prompt_loss_weight: 0.01
    learning_rate_multiplier: 0.05
organization_id:
  desc: null
  value: org-WuFLwmy1CYht2uDwZu37mDlB
model:
  desc: null
  value: curie
training_files:
  desc: null
  value:
    object: file
    id: file-8rseY2ZhNO5xbQki5SUAHveC
    purpose: fine-tune
    filename: data/SBIC.v2.agg.trn.tiny.social-bias.promted_prepared.jsonl
    bytes: 291534
    created_at: 1683954564
    status: processed
    status_details: null
validation_files:
  desc: null
  value:
    object: file
    id: file-52QkjLqLHKpwVYvCrSPD7Tz6
    purpose: fine-tune
    filename: data/SBIC.v2.agg.dev.tiny.social-bias.promted_prepared.jsonl
    bytes: 37908
    created_at: 1683954566
    status: processed
    status_details: null
result_files:
  desc: null
  value:
    object: file
    id: file-F3oFRj9cQnU7VDRyjkPs81Jc
    purpose: fine-tune-results
    filename: compiled_results.csv
    bytes: 104677
    created_at: 1683955800
    status: processed
    status_details: null
created_at:
  desc: null
  value: '2023-05-13T10:39:27'
updated_at:
  desc: null
  value: 1683955800
status:
  desc: null
  value: succeeded
fine_tuned_model:
  desc: null
  value: curie:ft-personal-2023-05-13-05-29-59
_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.15.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683956993.732265
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.10.7
      5: 0.15.2
      8:
      - 3
      - 5
n_train:
  desc: null
  value: 1771
n_valid:
  desc: null
  value: 233
